version: 2.1

workflows:
  PR_workflow:
    when: << pipeline.parameters.pr_webhook >>
    jobs:
      - pr_job

  commit_workflow:
    when: 
      not: << pipeline.parameters.pr_webhook >>
    jobs:
      - job1

jobs:
  job1:
    executor: base
    steps:
      - run: echo "hello from job1"

  pr_job:
    executor: base
    steps:
      - run: echo "hello there was a PR"
      - run: echo "<< pipeline.parameters.pr_webhook >> << pipeline.parameters.pr_base >> << pipeline.parameters.pr_sha >> << pipeline.parameters.pr_number >> << pipeline.parameters.pr_action >> "
      - run:
          # https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests#search-by-commit-sha
          name: Get PR number from hash pipeline param 
          command: |
            echo "use the above API"
      - run:
          name: Get PR Info
          # https://circleci.com/developer/orbs/orb/narrativescience/ghpr#commands-get-pr-info
          command: |
            echo "customize that above command to use the pipeline parameter PR number"
      - run: 
          name: Run steps needed after PR info is here
          command: |
            echo "some tests"    
      - run:
          name: Interact with the bot
          command: |
            echo "some commands here to interact with the bot"  
      - run: 
          name: Or send only on failure
          command: |
            echo "interact with bot"
          when: on_fail
executors:
  base:
    docker: 
      - image: cimg/base:stable

orbs:
  ghpr: narrativescience/ghpr@1.1.1

parameters:
  pr_webhook:
    type: boolean
    default: false
  pr_user:
    type: string
    default: "hueylewis"
  pr_base:
    type: string
    default: "dev"
  pr_sha:
    type: string
    default: 123
  pr_number:
    type: string
    default: 1
  pr_action:
    type: string
    default: "opened"
