version: 2.1

workflows:
  PR_workflow:
    when: << pipeline.parameters.pr_from_gh >>
    jobs:
      - pr_job

  commit_workflow:
    when: 
      not: << pipeline.parameters.pr_from_gh >>
    jobs:
      - job1

jobs:
  job1:
    executor: base
    steps:
      - run: echo "hello from job1"

  pr_job:
    executor: base
    steps:
      - run: echo "hello there was a PR"
      - run: echo "<< pipeline.parameters.committer >> << pipeline.parameters.base >> << pipeline.parameters.SHA >>"
      - run:
          name: Get PR Info
          # https://circleci.com/developer/orbs/orb/narrativescience/ghpr#commands-get-pr-info
          command: |
            echo "customize that above command to use the pipeline parameter PR number"

executors:
  base:
    docker: 
      - image: cimg/base:stable

orbs:
  ghpr: narrativescience/ghpr@1.1.1

parameters:
  pr_from_gh:
    type: boolean
    default: false
  committer:
    type: string
    default: "someone"
  base:
    type: string
    default: "dev"
  SHA:
    type: string
    default: "123"
  pr_number:
    type: integer
    default: 1